### ISSUE TITLE
I wish to set the output directory for the bundles

### ISSUE THREAD

**Issue by andres-sinapsis** [jSherz/terraform-provider-node-lambda-packager#5]
Hey @jSherz great work the module, it is super helpful. 

I wonder if it is possible to set the folder for the bounder output, instead of using the same entry point folder which creates a lot of noise in the project.

Thanks.

**Comment by jSherz** [comment]
Hey @andres-sinapsis - please submit a pull request and I'll be very happy to merge it.

**Comment by NinoScript** [comment]
Hey, I need this too and for the same reason, so I'll do it.

**Comment by jSherz** [comment]
This has now been published!

Thank you @andres-sinapsis for the suggestion, and @NinoScript for implementing it.

```terraform
terraform {
  required_providers {
    node-lambda-packager = {
      source = "jSherz/node-lambda-packager"
      version = "1.2.0"
    }
  }
}
```

**Comment by YikaiHu** [comment]
This feature is really very helpful !!!
Thank you @NinoScript  and @andres-sinapsis
